### ISSUE TITLE
How to call api

### ISSUE THREAD

**Issue by vuonghung12** [davidnx/NextjsStaticHosting-AspNetCore#2]
Hi, I have set option 
```
    "DevServer": "http://localhost:3000/",
    "ProxyToDevServer": true
```

When I'm trying call api http://localhost:3000/api/WeatherForecast/get => throw this message
how to fix this bro

> Server Error
> Error: self-signed certificate

> This error happened while generating the page. Any console logs will be displayed in the terminal window.
> Call Stack
> TLSSocket.onConnectSecure
> node:_tls_wrap (1534:34)
> TLSSocket.emit
> node:events (513:28)
> TLSSocket.emit
> node:domain (489:12)
> TLSSocket._finishInit
> node:_tls_wrap (948:8)
> ssl.onhandshakedone
> node:_tls_wrap (729:12)

**Comment by davidnx** [comment]
This library has nothing to do with TLS certificates and bindings, so your problem is (most likely) unrelated to this project.

Debugging suggestion: You may want to get the sample weather app to work first, and then try adding this library once you have a basic setup running. This will help you ensure you have a solid foundation that works, and then you can start changing it.

In order to help you better, can you share the complete console outputs and, if possible, a link to a minimal repro project that shows the error you are facing?

**Comment by vuonghung12** [comment]
hi, here is my code
https://github.com/vuonghung12/TestNextjsNetCore
just start from visual studio
then go to url http://localhost:3000/api/WeatherForecast/get
the error will display
hope you can help

**Comment by davidnx** [comment]
Unfortunately your problem is outside the scope of this library. As mentioned, I suggest that you remove everything related to NextjsStaticHosting-AspNetCore from your project, get that working, and then add NextjsStaticHosting-AspNetCore back. Please file a new issue if you have a problem that is specifically about this library. You may also want to pursue other ASP .NET Core community and support channels for assistance.
